/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arungfutsall;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author Lenovo
 */
public class LoginAdmin extends javax.swing.JFrame {
private JTextField tfUsername;
private JPasswordField pfPassword;
private JButton btnLogin;
   public LoginAdmin() {
        setTitle("Login Admin - Arung Futsal");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(400, 270);
        setLocationRelativeTo(null);
        setResizable(false);

        // Panel Utama
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBackground(Color.WHITE);

        // Header
        JLabel lblTitle = new JLabel("Login Admin - Arung Futsal", SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setOpaque(true);
        lblTitle.setBackground(new Color(52, 167, 240));
        lblTitle.setBorder(BorderFactory.createEmptyBorder(18, 0, 18, 0));
        panel.add(lblTitle, BorderLayout.NORTH);

        // Form login
        JPanel form = new JPanel(new GridBagLayout());
        form.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 14, 10, 14);
        gbc.anchor = GridBagConstraints.WEST;

        JLabel lblUser = new JLabel("Username:");
        lblUser.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        tfUsername = new JTextField(15);
        tfUsername.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        tfUsername.setBorder(BorderFactory.createLineBorder(new Color(52, 167, 240), 2));

        JLabel lblPass = new JLabel("Password:");
        lblPass.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        pfPassword = new JPasswordField(15);
        pfPassword.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        pfPassword.setBorder(BorderFactory.createLineBorder(new Color(52, 167, 240), 2));

        btnLogin = new JButton("Login");
        btnLogin.setBackground(new Color(52, 167, 240));
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFont(new Font("Segoe UI", Font.BOLD, 18));
        btnLogin.setFocusPainted(false);
        btnLogin.setBorder(BorderFactory.createEmptyBorder(8, 0, 8, 0));

        gbc.gridx = 0; gbc.gridy = 0; form.add(lblUser, gbc);
        gbc.gridx = 1; gbc.gridy = 0; form.add(tfUsername, gbc);
        gbc.gridx = 0; gbc.gridy = 1; form.add(lblPass, gbc);
        gbc.gridx = 1; gbc.gridy = 1; form.add(pfPassword, gbc);
        gbc.gridx = 0; gbc.gridy = 2; gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        form.add(btnLogin, gbc);

        panel.add(form, BorderLayout.CENTER);

        setContentPane(panel);

        // Action: tekan enter = login
        pfPassword.addActionListener(e -> btnLogin.doClick());
        tfUsername.addActionListener(e -> btnLogin.doClick());

        // Action: klik Login
        btnLogin.addActionListener(e -> cekLogin());
    }

    private void cekLogin() {
        String user = tfUsername.getText();
        String pass = new String(pfPassword.getPassword());

        if("admin".equals(user) && pass.equals("adminarung123")) {
            // Login berhasil
            this.dispose(); // tutup window login
            new DashboardAdmin().setVisible(true); // buka dashboard
        } else {
            JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
            pfPassword.setText("");
            tfUsername.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new LoginAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
