/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.LapanganController;
import model.Lapangan;
import utils.Validasi;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class LapanganPanel extends javax.swing.JPanel {
    private LapanganController controller = new LapanganController();
    private JTable table;
    private DefaultTableModel tableModel;
    private JTextField tfNama, tfHarga, tfCari;
    private JCheckBox cbStatus;
    private JButton btnTambah, btnHapus;
    /**
     * Creates new form LapanganPanel
     */
    public LapanganPanel() {
        setLayout(new BorderLayout());

        tfNama = new JTextField(10);
        tfHarga = new JTextField(10);
        tfCari = new JTextField(10);
        cbStatus = new JCheckBox("Aktif");

        btnTambah = new JButton("Tambah");
        btnHapus = new JButton("Hapus");

        tableModel = new DefaultTableModel(new String[]{"Nama", "Harga", "Status"}, 0);
        table = new JTable(tableModel);

        JPanel inputPanel = new JPanel();
        inputPanel.add(new JLabel("Nama:")); inputPanel.add(tfNama);
        inputPanel.add(new JLabel("Harga:")); inputPanel.add(tfHarga);
        inputPanel.add(cbStatus);
        inputPanel.add(btnTambah);
        inputPanel.add(btnHapus);
        inputPanel.add(new JLabel("Cari:")); inputPanel.add(tfCari);

        add(inputPanel, BorderLayout.NORTH);
        add(new JScrollPane(table), BorderLayout.CENTER);

        btnTambah.addActionListener(e -> tambahLapangan());
        btnHapus.addActionListener(e -> hapusLapangan());
        tfCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { refreshTabel(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { refreshTabel(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { refreshTabel(); }
        });
    }
    
    private void tambahLapangan() {
        if (Validasi.isKosong(tfNama) || Validasi.isKosong(tfHarga)) {
            JOptionPane.showMessageDialog(this, "Nama dan harga tidak boleh kosong");
            return;
        }
        Lapangan l = new Lapangan(tfNama.getText(), Double.parseDouble(tfHarga.getText()), cbStatus.isSelected());
        controller.tambahLapangan(l);
        refreshTabel();
    }
    
    private void hapusLapangan() {
        int row = table.getSelectedRow();
        if (row >= 0) {
            controller.hapusLapangan(row);
            refreshTabel();
        }
    }
    
    private void refreshTabel() {
        String keyword = tfCari.getText();
        List<Lapangan> list = controller.cariLapangan(keyword);
        tableModel.setRowCount(0);
        for (Lapangan l : list) {
            tableModel.addRow(new Object[]{l.getNama(), l.getHarga(), l.isStatus() ? "Aktif" : "Tidak Aktif"});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
