/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package arungfutsall;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

public class PanelLaporan extends JPanel {
    private JTable table;
    private DefaultTableModel tableModel;
    private Connection conn;
    
    public PanelLaporan() {
        setLayout(new BorderLayout());
        JLabel label = new JLabel("Laporan Pembayaran", SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 16));
        add(label, BorderLayout.NORTH);

        String[] columns = {"ID Booking", "Nama", "Lapangan", "Tanggal", "Mulai", "Selesai", "Jumlah Bayar", "Status"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override public boolean isCellEditable(int row, int col) { return false; }
        };
        table = new JTable(tableModel);
        add(new JScrollPane(table), BorderLayout.CENTER);

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/arung_futsal", "root", "");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi ke database.");
        }

        loadLaporan();
    }

    public void loadLaporan() {
        tableModel.setRowCount(0);
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM penyewaan ORDER BY id DESC");
            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_pelanggan");
                String lapangan = rs.getString("lapangan");
                String tanggal = rs.getString("tanggal");
                String jamMulai = rs.getString("jam_mulai").substring(0,5);
                String jamSelesai = rs.getString("jam_selesai").substring(0,5);
                int jumlahBayar = hitungTotalBayar(rs.getString("jam_mulai"), rs.getString("jam_selesai"));
                String status = "Lunas";
                tableModel.addRow(new Object[]{
                        id, nama, lapangan, tanggal, jamMulai, jamSelesai, "Rp" + jumlahBayar, status
                });
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private int hitungTotalBayar(String jamMulai, String jamSelesai) {
        try {
            int start = Integer.parseInt(jamMulai.split(":")[0]);
            int end = Integer.parseInt(jamSelesai.split(":")[0]);
            int durasi = end - start;
            if (durasi < 1) durasi = 1; // minimal 1 jam
            return durasi * 80000;
        } catch (Exception e) {
            return 80000;
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
